#: import MDBoxLayout kivymd.uix.boxlayout
#: import MDLabel kivymd.uix.label.label
#: import MDBoxLayout kivymd.uix.boxlayout
#: import MDList kivymd.uix.list.list
#: import MDScrollView kivymd.uix.scrollview
#: import MDStackLayout kivymd.uix.stacklayout
#: import MDTextField kivymd.uix.textfield.textfield

#: import MDRectangleFlatButton kivy.uix.button
#: import MDFlatButton kivy.uix.button


<Workspace>:
    name: 'workspace'
    MDLabel:
        text: '1'